//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInsurance.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyInsurance.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در عملیات به وجود آمده است.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشش جراحی.
        /// </summary>
        public static string Covarage1 {
            get {
                return ResourceManager.GetString("Covarage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشش دندانپزشکی.
        /// </summary>
        public static string Covarage2 {
            get {
                return ResourceManager.GetString("Covarage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوشش بستری.
        /// </summary>
        public static string Covarage3 {
            get {
                return ResourceManager.GetString("Covarage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت درخواست با پوشش تکراری میسر نمی باشد.
        /// </summary>
        public static string CoverageDuplicate {
            get {
                return ResourceManager.GetString("CoverageDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب حداقل یک پوشش اجباری است.
        /// </summary>
        public static string CoverageNumberMinimumEntry {
            get {
                return ResourceManager.GetString("CoverageNumberMinimumEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر پوشش فعالی وجود ندارد.
        /// </summary>
        public static string DoNotAnyActiveCoverages {
            get {
                return ResourceManager.GetString("DoNotAnyActiveCoverages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در عملیات به وجود آمده است.
        /// </summary>
        public static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشکلی در عملیات ذخیره سازی بوجود آمده است.
        /// </summary>
        public static string GeneralSavingError {
            get {
                return ResourceManager.GetString("GeneralSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک یا چند پوشش مورد نظر معتبر نمی باشد.
        /// </summary>
        public static string InvalidCoverage {
            get {
                return ResourceManager.GetString("InvalidCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار معتبر برای {0} بایستی بین بازه {1} و {2} باشد.
        /// </summary>
        public static string InvalidCoverageRangeValue {
            get {
                return ResourceManager.GetString("InvalidCoverageRangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده اشتباه است.
        /// </summary>
        public static string NationalCodeInvalid {
            get {
                return ResourceManager.GetString("NationalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی اجباری است.
        /// </summary>
        public static string NationalCodeRequired {
            get {
                return ResourceManager.GetString("NationalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد درخواستی یافت نشد.
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواستی یافت نشد.
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما با موفقیت ثبت شد.
        /// </summary>
        public static string RequestRegistred {
            get {
                return ResourceManager.GetString("RequestRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان اجباری است.
        /// </summary>
        public static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر تکراری است.
        /// </summary>
        public static string UserDuplicate {
            get {
                return ResourceManager.GetString("UserDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر ثبت شد.
        /// </summary>
        public static string UserRegistered {
            get {
                return ResourceManager.GetString("UserRegistered", resourceCulture);
            }
        }
    }
}
